#!/bin/csh
##edited by JEFF 2017/09/21

cd $1
ls -dF 1111* > $1/filetmp #抓取有1111開頭的目錄名
set Original = `pwd`
set Original = "$Original/"
set i=1
set Head_111_Folder =("` cat $1/filetmp |  grep "/" `")
set Head_111_Folder_count = $#Head_111_Folder
while ( $i <= $Head_111_Folder_count )
 echo "$Original$Head_111_Folder[$i]"
 @ i++
end
rm -f $1/filetmp

