#!/bin/csh
##edited by JEFF 2017/09/22
cd $1
ls -F > $1/filetmp
set Original = `pwd`
set Original = "$Original/"
set i=1
set Folder = ("` cat $1/filetmp | grep "/" `")
set Folder_count = $#Folder
while ( $i <= $Folder_count )
 set j=1 
 set Path_Folder = "$Original$Folder[$i]"
 cd "$Path_Folder"
 ls -F  > ./filetmp               #列出該目錄的文件檔名稱
 set docu = ("` cat ./filetmp | grep -v "/" `")
 set docu_count = $#docu
 while ( $j <= "$docu_count" )
  set Inc_1111_docu_count = "` cat ./"$docu[$j]" | grep -c "1111" `"
  set Inc_iiii_docu_count = "` cat ./"$docu[$j]" | grep -c "iiii" `"
  if ( "$Inc_1111_docu_count" > "0" && "$Inc_iiii_docu_count" > "0" ) then
    echo "$Original$Folder[$i]$docu[$j]"
  endif
  @ j++
 end
 rm -f ./filetmp
 @ i++
end
rm -f $1/filetmp
